### ISSUE TITLE
Special handling of PEM file no longer needed?

### ISSUE THREAD

**Issue by perlDreamer** [xaicron/p5-Net-APNs-HTTP2#1]
There is a note about the P8/PEM files in the module docs:

Universal Push Notification Client SSL Certificate. But, can not use this auth key as it is. Please convert key as follows:

This is caused by Crypt::PK::ECC.  However, a recent update (March 25, 2018) on that module says that the issue has been fixed:

0.059   2018-03-25
        - new Crypt::Digest::Keccak(224|256|384|512)
        - new methods sign_hash_rfc7518 + verify_hash_rfc7518 (Crypt::PK::ECC)
        - improved import of pkcs#8 private keys (Crypt::PK::ECC)
        - improved export allowing "compressed" variants (Crypt::PK::ECC)
        **- fix #28 Apple's APNS pkcs8 auth key import fails (Crypt::PK::ECC)**
        - fix cpantesters failure (5.8.1 related)

I don't think that would have any impact on the code, but it would make work easier for users of your module.

**Comment by xaicron** [comment]
Thank you for information!
I'll check it :)

**Comment by xaicron** [comment]
Shipped 0.02. Thank you!
